apiVersion: 2.0
kind: ServiceConfig
metadata:
  serviceConfigVersion: 1.3-STAGE
  serviceId: aex-strategy-listener
  authzPolicies:
    adminUI:
      adminGroups:
        - "apparel-precision-kitt"
    git:
      org: "ApparelPrecision"
      repo: "aex-strategy-listener"
      branch: "main"
  externallyReferencedServiceConfig:
    - serviceId: "AEX_KAFKA_COMMON"
      serviceConfigVersion: "1.0-STAGE"
  notifications:
    slack:
      channel: apparel-precision-ops
configDefinitions:
  kafkaConfig:
    description: "Kafka Configurations"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "aex.clp.ap.kafka.server":
        description: "Kafka Broker list for AEX current line plan"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "kafka-1301504412-1-1404508139.scus.kafka-v2-secured-shared3-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1301504412-2-1404508142.scus.kafka-v2-secured-shared3-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1301504412-3-1404508145.scus.kafka-v2-secured-shared3-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1301504412-4-1404508148.scus.kafka-v2-secured-shared3-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1301504412-5-1404508151.scus.kafka-v2-secured-shared3-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1301504412-6-1404508154.scus.kafka-v2-secured-shared3-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093"
      "aex.plan.definition.kafka.topic":
        description: "Kafka Topic for AEX Plan Definition"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "aex_plan_definition_stg"
      "aex.clp.ap.kafka.topic":
        description: "Kafka Topic for AEX current line plan"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "aex_line_plan_stg"
      "aex.clp.ap.kafka.consumer.group-id":
        description: "Group Id for current line plan kafka topic"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "aex.strategy.service.stg"
      "aex.plandefinition.ap.kafka.consumer.group-id":
        description: "Group Id for plan definition changes to strategy service kafka topic"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "aex.plandefinition.strategy.service.stg"
      "kafka.sessionTimeout":
        description: "Session Timeout for Kafka consumer connections"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "50000"
      "kafka.heartbeatInterval":
        description: "Heartbeat Interval for Kafka consumer connections"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "12000"
      "kafka.autoOffsetReset":
        description: "Auto Offset Reset config for Kafka consumer connections"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "latest"
      "kafka.enableAutoCommit":
        description: "Autocommit Enable config for Kafka consumer connections"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "false"
      "kafka.consumer.accepted.types":
        description: "Accepted 'type' attribute in payload received by kafka consumer"
        type: "STRING"
        kind: "MULTI"
        defaultValues:
          - "create"
          - "update"
          - "delete"
      "kafka.consumer.accepted.channels":
        description: "Accepted 'channel' attribute in payload received by kafka consumer"
        type: "STRING"
        kind: "MULTI"
        defaultValues:
          - "store"
          - "omni"
          - "online"
      "kafka.consumer.accepted.updates":
        description: "Accepted update events in payload received by kafka consumer"
        type: "STRING"
        kind: "MULTI"
        defaultValues:
          - "finelineName"
          - "channel"
          - "traitChoice"
          - "preferredFixtureType"
          - "preferredFixtureType2"
          - "preferredFixtureType3"
          - "preferredFixtureType4"
          - "transactableStartWk"
          - "transactableEndWk"
          - "colorName"
          - "altFinelineName"
          - "altStyleDesc"
          - "altCcDesc"
          - "colorFamily"
          - "outFitting"
          - "likeAssociation"
          - "brandId"
          - "brandName"
          - "productDimDesc"
          - "productDimId"
      "kafka.consumer.initial.load.flag":
        description: "Initial Load to sync plans between LP to other capabilities"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "false"
      "kafka.consumer.assort.product.flag":
        description: "Initial Load to sync plans between LP to other capabilities"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "false"
      "kafka.consumer.size.pack.flag":
        description: "Initial Load to sync plans between LP to other capabilities"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "true"
  midasConfig:
    description: "Midas Data API Service to Service Authentication"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "midas.baseURL":
        description: "Midas api base url"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "http://midas-data-api.stg.midas-api.catdev.prod.us.walmart.net/api/workflow/v1/execute"
      "midas.clickhouse.table":
        description: "midas clickhouse table"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "omni_item_channel_sales_wkly_v4_dist"
      "midas.header.contentType":
        description: "Midas api header content type"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "application/json"
      "midas.header.consumer":
        description: "Midas api header consumer Id"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "13705f9d-3eb8-46b5-b2c1-63a1b569af4c"
      "midas.header.signatureKeyVersion":
        description: "Midas api header signature Key Version"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "1"
      "midas.header.signatureAuthFlag":
        description: "Midas api header signature Auth Flag"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "true"
      "midas.header.signatureTS":
        description: "Midas api header signature TS"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "1639068838648"
      "midas.header.tenant":
        description: "Midas api header tenant"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "aex"
      "midas.apRankingMetricsQuery":
        description: "To fetch AP Ranking Metrics from ClickHouse database workflow"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "{\"query\": { \"select\": [ { \"field\": \"*\" } ], \"from\": \"get_apRanking_metrics\", \"params\": { \"l1Id\": \"%s\", \"l2Id\": \"%s\", \"finelineNbr\": \"%s\", \"season\": \"%s\", \"fiscalYear\": \"%s\"}}}"
      "midas.spGetStoreSizeProfilesQuery":
        description: "To retrieve store size profiles by fineline/color"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "{\"query\":{\"select\":[{\"field\":\"*\"}],\"from\":\"get_store_size_profiles\",\"params\":{\"season\":\"%s\",\"deptNbr\":\"%s\",\"finelineNbr\":\"%s\",\"colorFamily\":\"%s\",\"year\":\"%s\"}}}"
      "midas.spGetStoreSizeProfilesQuery_v2":
        description: "To retrieve store size profiles by fineline/colorfamilies"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "{\"query\":{\"select\":[{\"field\":\"*\"}],\"from\":\"get_store_size_profiles_v2\",\"params\":{\"season\":\"%s\",\"deptNbr\":\"%s\",\"deptCatgNbr\":\"%s\",\"deptSubCatgNbr\":\"%s\",\"finelineNbr\":\"%s\",\"colorFamilies\":\"%s\",\"year\":\"%s\"}}}"
      "midas.spGetOnlineSizeProfilesQuery":
        description: "To retrieve online size profiles base baseItemId/color"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "{\"query\":{\"select\":[{\"field\":\"*\"}],\"from\":\"get_ecomm_size_profiles\",\"params\":{\"season\":\"%s\",\"deptNbr\":\"%s\",\"baseItemId\":\"%s\",\"colorFamily\":\"%s\",\"year\":\"%s\"}}}"
      "midas.spGetOnlineSizeProfilesQuery_v2":
        description: "To retrieve online size profiles base baseItemId/color"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "{\"query\":{\"select\":[{\"field\":\"*\"}],\"from\":\"get_ecomm_size_profiles_v2\",\"params\":{\"season\":\"%s\",\"deptNbr\":\"%s\",\"baseItemIds\":\"%s\",\"colorFamilies\":\"%s\",\"year\":\"%s\"}}}"
  httpConfig:
    description: "HTTP Configurations"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "http.connectTimeout":
        description: "Connection Timeout for HTTP Calls"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 18000
      "http.connectionRequestTimeout":
        description: "Connection Request Timeout for HTTP Calls"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 18000
      "http.readTimeout":
        description: "Read Timeout for HTTP calls"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 18000
      "http.short.connectTimeout":
        description: "Short Connection Timeout for HTTP Calls"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 5000
      "http.short.connectionRequestTimeout":
        description: "Short Connection Request Timeout for HTTP Calls"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 5000
      "http.short.readTimeout":
        description: "Short Read Timeout for HTTP calls"
        type: "INTEGER"
        kind: "SINGLE"
        defaultValue: 5000
  strategyConfig:
    description: "Strategy Configurations"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "strategy.baseUrl":
        description: "Strategy Base URL"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "https://strategy.aex.stg.walmart.net"
      "strategy.accepted.fixture.updates":
        description: "Accepted fixture updates forfixture strategy update"
        type: "STRING"
        kind: "MULTI"
        defaultValues:
          - "preferredFixtureType"
          - "preferredFixtureType2"
          - "preferredFixtureType3"
          - "preferredFixtureType4"
      "strategy.consumerId":
        description: "Strategy Consumer Id"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "baf1bb4a-8c4e-431a-81a9-5f3a9ea171b8"
      "strategy.appKey":
        description: "Strategy App Key"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "AEX_STRATEGY_SERVICE"
      "strategy.env":
        description: "Strategy Env"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "stg"
  ahsApiConfig:
    description: "AHS Api Header Configurations"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "strategy.sizeUrl":
        description: "AHS Size URL"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "http://attributehelper.apparel.stg.walmart.net/retrieveValuesByHierarchy"
      "strategy.sizeCustomerID":
        description: "AHS CustomerID for Size"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "baf1bb4a-8c4e-431a-81a9-5f3a9ea171b8"
      "strategy.sizeServiceName":
        description: "AHS Service Name"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "ATTRIBUTE-HELPER-SERVICE"
      "strategy.sizeApiEnv":
        description: "ENVIRONMENT"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "stg"
      "strategy.sizeAttributeName":
        description: "Attribute for which we want info from AHS"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "size"
      "strategy.consumerId":
        description: "Strategy Consumer Id"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "3083580c-161c-41f6-90de-eba73f02c564"
      "strategy.appKey":
        description: "Strategy App Key"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "AEX_STRATEGY_SERVICE"
      "strategy.env":
        description: "Strategy Env"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "stg"
      "size.pack.release.flag":
        description: "Size pack release flag"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "true"
  featureConfig:
    description: "This Configuration helps to enable-disable a feature"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "enable.deletePlanCategorySubCategory":
        description: "Flag to enable delete Plan Category,Sub-Category"
        type: "BOOLEAN"
        kind: "SINGLE"
        defaultValue: true
      "likeFinelineFeatureFlag":
        description: "Flag to enable like fineline feature"
        type: "BOOLEAN"
        kind: "SINGLE"
        defaultValue: true
      "kafka.errorHandling.enabled":
        description: "Feature Flag to enable Kafka Error Handling"
        type: "BOOLEAN"
        kind: "SINGLE"
        defaultValue: true
  sizePackConfig:
    description: "Size and Pack Accepted Updates"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "size.pack.accepted.updates":
        description: "Accepted updates for size and pack"
        type: "STRING"
        kind: "MULTI"
        defaultValues:
          - "colorFamily"
          - "colorName"
          - "channel"
          - "likeAssociation"
      "size.pack.plan.desc.feature.flag":
        description: "Flag to enable usage of default plan description value"
        type: "BOOLEAN"
        kind: "SINGLE"
        defaultValue: false
      "size.pack.plan.desc.value":
        description: "Plan description default value"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "S3 - FYE2024"
  retryConfig:
    description: "Config to help with retry of failed messages"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "aex.kafka.error.retry.url":
        description: "Url to retry failed messages"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "https://aex-strategy-listener.stg.walmart.net/retry"
      "aex.kafka.app.name":
        description: "App name to identify failed messages"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "AEX-STRATEGY-LISTENER"
  kafkaRedirectConfig:
    description: "Config to read and write to redirect topic"
    resolutionPaths:
      - default: "/envProfile/envName"
    properties:
      "aex.kafka.redirect.server":
        description: "Kafka Clusters for Redirect topic"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "kafka-1301504412-1-1758430482.scus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1301504412-2-1758430485.scus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1301504412-3-1758430488.scus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1301504412-4-1758430491.scus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1301504412-5-1758430494.scus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1301504412-6-1758430497.scus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1301504412-7-1758430500.scus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1301504412-8-1758430503.scus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1301504412-9-1758430506.scus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1301504412-10-1758430509.scus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1301504412-11-1758430512.scus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1301504412-12-1758430515.scus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1301504412-13-1758430518.scus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1301504412-14-1758430521.scus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1301504412-15-1758430524.scus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-southcentralus-10.prod.us.walmart.net:9093,kafka-1568317777-1-1758570137.wus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-westus2-7.westus2.prod.us.walmart.net:9093,kafka-1568317777-2-1758570140.wus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-westus2-7.westus2.prod.us.walmart.net:9093,kafka-1568317777-3-1758570143.wus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-westus2-7.westus2.prod.us.walmart.net:9093,kafka-1568317777-4-1758570146.wus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-westus2-7.westus2.prod.us.walmart.net:9093,kafka-1568317777-5-1758570149.wus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-westus2-7.westus2.prod.us.walmart.net:9093,kafka-1568317777-6-1758570152.wus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-westus2-7.westus2.prod.us.walmart.net:9093,kafka-1568317777-7-1758431500.wus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-westus2-7.westus2.prod.us.walmart.net:9093,kafka-1568317777-8-1758570155.wus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-westus2-7.westus2.prod.us.walmart.net:9093,kafka-1568317777-9-1758570158.wus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-westus2-7.westus2.prod.us.walmart.net:9093,kafka-1568317777-10-1758570161.wus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-westus2-7.westus2.prod.us.walmart.net:9093,kafka-1568317777-11-1758570164.wus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-westus2-7.westus2.prod.us.walmart.net:9093,kafka-1568317777-12-1758570167.wus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-westus2-7.westus2.prod.us.walmart.net:9093,kafka-1568317777-13-1758570170.wus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-westus2-7.westus2.prod.us.walmart.net:9093,kafka-1568317777-14-1758431521.wus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-westus2-7.westus2.prod.us.walmart.net:9093,kafka-1568317777-15-1758570173.wus.kafka-taas-shared7-stg.ms-df-messaging.stg-az-westus2-7.westus2.prod.us.walmart.net:9093"
      "aex.kafka.redirect.topic":
        description: "Kafka Redirect Topic Name"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "APM0010444-aex-kafka-DEV-aex-strategy-failure-redirect-stg"
      "aex.kafka.redirect.groupId":
        description: "Group Id to consume from Redirect topic"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "DEV-aex-strategy-failure-redirect-stg"
      "aex.kafka.redirect.sessionTimeout":
        description: "Session Timeout for Redirect Topic"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "45000"
      "aex.kafka.redirect.heartbeatInterval":
        description: "Heartbeat interval for Redirect Topic"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "12000"
      "aex.kafka.redirect.autoOffsetReset":
        description: "Auto Offset Reset Config for Redirect Topic"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "earliest"
      "aex.kafka.redirect.enableAutoCommit":
        description: "Auto Commit Config for Redirect Topic"
        type: "STRING"
        kind: "SINGLE"
        defaultValue: "false"
